#!/usr/bin/env bash
function help() {
  echo
  echo
  echo "add cac pkcs11 URI to git repo config"
  echo "$ git-config-cac -m set -l <token prefix>"
  echo
  echo "remove cac pkcs11 URI from git repo config"
  echo "$ git-config-cac -m unset"
  echo
  echo "test cac with test URL"
  echo "$ git-config-cac -m test_git -l <token prefix> -u <https://URL>"
  echo "$ git-config-cac -m test_curl -l <token prefix> -u <https://URL>"
  echo
  echo "-m    mode [set | unset | test_git | test_curl]"
  echo "-k    suffix for private key identifier default=PIV%20AUTH%20pubkey"
  echo "-c    suffix for public key identifier default=PIV%20AUTH%20key"
  echo "-l    prefix for token identifier"
  echo "-u    test URL for git or curl test"
}
# TODO usage documentation

function get_cert() {
  read -s -p "Enter PKCS#11 token PIN:  " PIN
  echo
  echo "Searching for token starting with $PRETOKEN"
  TOKEN=($(p11tool --list-tokens | grep -ioe "token=$PRETOKEN\+[a-zA-Z0-9._%]\+"))
  echo "Found token $TOKEN"
  echo
  echo "Searching for public key label ending with $CERTID"
  PUBKEY=($(p11tool --list-all --detailed-url --only-urls --login --set-pin=$PIN pkcs11:$TOKEN | grep -oe "$TOKEN\+[a-zA-Z0-9=%.;]\+$CERTID"))
  echo "Found public key $PUBKEY" 
  echo
  echo "Searching for private key label ending with $KEYID"
  PRIVKEY=($(p11tool --list-all --detailed-url --only-urls --login --set-pin=$PIN pkcs11:$TOKEN | grep -oe "$TOKEN\+[a-zA-Z0-9=%.;]\+$KEYID"))
  echo "Found private key $PRIVKEY"
  echo
}

# Set CAC for local git repo
function set_git() {
  get_cert
  echo "Setting local git repository with http.sslcert, http.sslkey, etc."
  echo
  git config --local http.sslbackend openssl
  git config --local http.sslengine pkcs11
  git config --local http.sslcert "pkcs11:$PUBKEY"
  git config --local http.sslcerttype ENG
  git config --local http.sslkey "pkcs11:$PRIVKEY"
  git config --local http.sslkeytype ENG
}

# Unset CAC for local git repo
function unset_git() {
  echo "Unsetting git http.sslcert, http.sslkey, etc."
  echo
  git config --local --unset http.sslcert
  git config --local --unset http.sslcerttype
  git config --local --unset http.sslkey
  git config --local --unset http.sslkeytype
  git config --local --unset http.sslengine
  git config --local --unset http.sslbackend
}

function test_git() {
  get_cert
  echo Testing CAC/ECA certificates with git...
  echo Using: $URL
  echo
  # set verbosity for git trace
  # export GIT_TRACE=1
  export GIT_CURL_VERBOSE=1

  # set verbosity for OpenSC
  # export OPENSC_DEBUG=3

  echo -------------------------------------
  $(brew --prefix git-https-cac)/bin/git \
    -c http.sslverify=false \
    -c http.sslcert="pkcs11:$PUBKEY" -c http.sslcerttype=ENG \
    -c http.sslkey="pkcs11:$PRIVKEY" -c http.sslkeytype=ENG \
    -c http.sslbackend=openssl
    -c http.sslengine=pkcs11 \
    fetch --dry-run $URL 2> test_git_out.txt
}

function test_curl() {
  get_cert
  echo Testing CAC/ECA certificates with curl...
  echo Using: $URL
  echo
  # explicitly passing flags
  # set environment variables
  export CURL_SSL_BACKEND=openssl
  
  echo -------------------------------------
  $(brew --prefix curl)/bin/curl -v -L --engine pkcs11 \
    --cert "pkcs11:$PUBKEY" --cert-type ENG \
    --key "pkcs11:$PRIVKEY" --key-type ENG \
    --url "$URL" 2> test_curl_out.txt
}


# default public and private key suffixes
CERTID=PIV%20AUTH%20pubkey
KEYID=PIV%20AUTH%20key
# default git test branch
BRANCH=main

while getopts 'l:m:u:k:c:h:' flag; do
  case "$flag" in
  c)
    CERTID=${OPTARG}
    ;;
  h)
    help
    exit;;
  l)
    PRETOKEN=${OPTARG}
    ;;
  m)
    M=${OPTARG}
    ;;
  k)
    KEYID=${OPTARG}
    ;;
  u)
    URL=${OPTARG}
    ;;
  *)
    echo "invalid flag"
    exit;;
  esac
done

case "$M" in
set)
  set_git
  ;;
unset)
  unset_git
  ;;
test_git)
  test_git
  ;;
test_curl)
  test_curl
  ;;
config)
  set_git
  ;;
esac
