#!/usr/bin/env bash
function help() {
  echo "add cac pkcs11 URI to git repo config"
  echo "git-config-cac -m set -l <last-name>"
  echo
  echo "remove cac pkcs11 URI from git repo config"
  echo "git-config-cac -m unset"
  echo
  echo "test cac with URL"
  echo "git-config-cac -m test_git -l <last-name> -u <https://URL>"
  echo "git-config-cac -m test_curl -l <last-name> -u <https://URL>"
}
# TODO usage documentation

function get_cert() {
  echo
  echo "Searching for token starting with $LNAME"
  CACCERT=($(p11tool --list-tokens | grep -ioe "token=$LNAME\+[a-zA-Z0-9._]\+"))
  echo "Found token $CACCERT"
  echo
  echo "Searching for certificate ending with $KEYID"
  CACKEY=($(p11tool --list-all-certs pkcs11:$CACCERT | grep -oe "$CACCERT\+[a-zA-Z0-9=%.;]\+$KEYID"))
  echo "Found certificate $CACKEY"
  echo
}

# Set CAC for local git repo
function set_git() {
  get_cert
  echo "Setting git http.sslcert, http.sslkey, etc."
  git config --local http.sslcert "pkcs11:$CACCERT"
  git config --local http.sslcerttype ENG
  git config --local http.sslkey "pkcs11:$CACKEY"
  git config --local http.sslkeytype ENG
  git config --local http.sslengine pkcs11
}

# Unset CAC for local git repo
function unset_git() {
  echo "Unsetting git http.sslcert, http.sslkey, etc."
  git config --local --unset http.sslcert
  git config --local --unset http.sslcerttype
  git config --local --unset http.sslkey
  git config --local --unset http.sslkeytype
  git config --local --unset http.sslengine
}

function test_git() {
  get_cert
  echo Testing git...
  # sh test_curl-https-cac.sh -c "$CACCERT" -k "$CACKEY" -u "$URL"
  # set verbosity for git trace
  # export GIT_TRACE=1
  # export GIT_CURL_VERBOSE=1
  # set verbosity for cac authentiaction
  # export OPENSC_DEBUG=3
  # export GIT_SSL_CERT_PASSWORD_PROTECTED=1
  export GIT_SSL_CERT="pkcs11:$CACCERT"
  export GIT_SSL_KEY="pkcs11:$CACKEY"
  export GIT_SSL_KEYTYPE=ENG
  export GIT_SSL_CERTTYPE=ENG
  export GIT_SSL_ENGINE=PKCS11
  #export GIT_SSL_BACKEND=openssl
  git fetch --dry-run $URL master
}

function test_curl() {
  get_cert
  echo Testing curl...
  echo Using: $URL
  SSL_CERT="pkcs11:$CACCERT"
  SSL_KEY="pkcs11:$CACKEY"
  # explicitly passing flags
  echo -------------------------------------
  echo Testing curl with flags
  curl -v --engine pkcs11 --cert "pkcs11:$CACCERT" --cert-type ENG --key "pkcs11:$CACKEY" --key-type ENG "$URL"
  # echo
  # echo --------------------------------------
  # echo Testing curl with environment variables
  # TODO currently broken
  # set curl option flags
  # export CULROPT_SSLCERT="pkcs11:$CACCERT"
  # export CURLOPT_SSLKEY="pkcs11:$CACKEY"
  # export CURLOPT_SSLCERTTYPE=ENG
  # export CURLOPT_SSLKEYTYPE=ENG
  # export CURLOPT_SSLENGINE=pkcs11
  # export CURL_SSL_BACKEND=openssl
  # curl -v "$URL"
}

while getopts 'l:m:u:k:' flag; do
  case "$flag" in
  l)
    LNAME=${OPTARG}
    ;;
  m)
    M=${OPTARG}
    ;;
  u)
    URL=${OPTARG}
    ;;
  k)
    KEYID=${OPTARG}
    ;;
  h)
    help
    exit;;
  *)
    echo "invalid flag"
    exit;;
  esac
done

# find the authentication key
KEYID=PIV%20Authentication


case "$M" in
set)
  set_git
  ;;
unset)
  unset_git
  ;;
test_git)
  test_git
  ;;
test_curl)
  test_curl
  ;;
config)
  set_git
  ;;
esac
